# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Dave Guarino
tagline:          'on technology, government, and change'
description:      'A place to think out loud about the less visible aspects of change.<br><br>Code for America <a href="http://www.codeforamerica.org/people/dave-guarino/">alumnus</a> (2013),<br>Code monkey,<br>Data wonk.'
url:              http://daguar.github.io

author:
  name:           'Dave Guarino'
  url:            https://twitter.com/allafarce

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
